#!/usr/bin/env bash
#
set -o nounset -o errexit
export PATH=/usr/sbin:/usr/bin:$PATH
net_if="`ip route show | grep default | awk '{print $5}'`"
echo $(ip addr show ${net_if} | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
